create table public.user (
        id bigint generated by default as identity,
        name varchar(255),
        phone_number varchar(255),
        thread_id varchar(255),
        primary key (id)
)

 create table item_transaction (
        id bigint generated by default as identity,
        transacao_id bigint not null,
        codigo_produto varchar(255),
        nome_produto varchar(255),
        descricao varchar(255),
        quantidade varchar(255),
        unidade varchar(255),
        valor_unitario numeric(38,2),
        valor_total numeric(38,2),
        primary key (id)
    )


 create table transaction (
        id bigint generated by default as identity,
        valor numeric(38,2),
        qtde_total_itens bytea,
        sub_total numeric(38,2),
        valor_pago numeric(38,2),
        cidade varchar(255),
        cnpj varchar(255),
        cpf varchar(255),
        endereco varchar(255),
        inscricao_estadual varchar(255),
        nome_estabelecimento varchar(255),
        taxa_imposto numeric(38,2),
        valor_imposto numeric(38,2),
        chave_acesso varchar(255),
        consumidor varchar(255),
        forma_pagamento varchar(255),
        tributo_estadual varchar(255),
        tributo_federal varchar(255),
        primary key (id)
    )


  alter table if exists item_transaction
       add constraint FKh28h1dsijvv75jas1n8ng18o5
       foreign key (transacao_id)
       references transaction